name = "AdaptiveSampling"
uuid = "8eadcf17-c760-4497-b196-5192eed4b985"
authors = ["Federico Cerisola <federico@cerisola.net>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
